// lib/constants.ts
import { Product, Ally, GrupoEmpresa } from "./types";

export const CONTACT = {
  phone: "+57 321 460 1590",
  whatsapp: "https://wa.me/573214601590",
  whatsappMessage: "https://wa.me/573214601590?text=Hola%2C%20me%20interesa%20conocer%20m%C3%A1s%20sobre%20los%20productos%20Eliana%20Zaia",
  email: "juan@elianazaia.com",
  location: "Zipaquira, Cundinamarca, Colombia",
  sloganB2C: "Un antojo para todos los dias",
  sloganB2B: "Tu lo imaginas, nosotros lo creamos",
} as const;

export const PRODUCTS: Product[] = [
  {
    id: "creme-brulee",
    name: "Creme Brulee",
    weight: "120g",
    category: "premium",
    description: "La fusión perfecta entre la tradición francesa y el toque latino de Eliana Zaia.",
    longDescription: "Nuestro Crème Brûlée artesanal combina una base cremosa de vainilla natural con una capa de caramelo crocante perfectamente torchado. Cada porción es elaborada con ingredientes seleccionados, siguiendo la receta que ha cautivado a miles de colombianos desde 2010.",
    image: "/images/products/creme-brulee.jpg",
    packagingImage: "/images/packaging/creme-brulee.jpg",
    featured: true,
    ingredients: ["Leche fresca", "Huevos", "Azúcar", "Vainilla natural", "Crema de leche"],
    relatedProducts: ["cheesecake", "leche-asada", "flan-de-caramelo"],
    seo: {
      h1: "Crème Brûlée — Postre artesanal colombiano",
      metaTitle: "Crème Brûlée Artesanal | Eliana Zaia",
      metaDescription: "Crème Brûlée artesanal con caramelo crocante y base cremosa de vainilla. Postre premium de Eliana Zaia, disponible en las principales cadenas de Colombia.",
      keywords: ["creme brulee artesanal", "postre premium colombia", "creme brulee colombiano"],
      seoContent: "",
      faq: [],
    },
  },
  {
    id: "cheesecake",
    name: "Cheesecake",
    weight: "100g",
    category: "premium",
    description: "Textura sedosa y sabor inconfundible. El cheesecake que redefine la categoría.",
    longDescription: "Cheesecake cremoso elaborado con queso crema de primera calidad y una base crocante. La receta de Eliana Zaia logra el balance perfecto entre dulzura y acidez, con una textura que se deshace en cada bocado.",
    image: "/images/products/cheesecake.jpg",
    packagingImage: "/images/packaging/cheesecake.jpg",
    featured: true,
    ingredients: ["Queso crema", "Galleta", "Mantequilla", "Azúcar", "Huevos"],
    relatedProducts: ["creme-brulee", "tres-leches", "flan-de-chocolate"],
    seo: {
      h1: "Cheesecake — Postre artesanal colombiano",
      metaTitle: "Cheesecake Artesanal | Eliana Zaia",
      metaDescription: "Cheesecake cremoso artesanal con base crocante. Postre premium de Eliana Zaia disponible en supermercados de Colombia.",
      keywords: ["cheesecake artesanal", "cheesecake colombia", "postre premium"],
      seoContent: "",
      faq: [],
    },
  },
  {
    id: "leche-asada",
    name: "Leche Asada",
    weight: "120g",
    category: "clasico",
    description: "La receta de la abuela, perfeccionada con técnica profesional.",
    longDescription: "La Leche Asada de Eliana Zaia rescata una de las recetas más queridas de la tradición latinoamericana. Elaborada con leche fresca y horneada lentamente hasta lograr su característico dorado, cada porción es un viaje a los sabores de la infancia.",
    image: "/images/products/leche-asada.jpg",
    packagingImage: "/images/packaging/leche-asada.jpg",
    featured: true,
    ingredients: ["Leche fresca", "Huevos", "Azúcar", "Canela", "Vainilla"],
    relatedProducts: ["arroz-con-leche", "postre-de-natas", "flan-de-caramelo"],
    seo: {
      h1: "Leche Asada — Postre artesanal colombiano",
      metaTitle: "Leche Asada Artesanal | Eliana Zaia",
      metaDescription: "Leche Asada artesanal horneada lentamente con receta tradicional. Postre clásico de Eliana Zaia en las principales cadenas de Colombia.",
      keywords: ["leche asada", "postre tradicional colombiano", "leche asada artesanal"],
      seoContent: "",
      faq: [],
    },
  },
  {
    id: "tres-leches",
    name: "Tres Leches",
    weight: "120g",
    category: "clasico",
    description: "Tres tipos de leche en perfecta armonía. Húmedo, dulce, irresistible.",
    longDescription: "El Tres Leches de Eliana Zaia es la expresión más pura de este clásico latinoamericano. Bizcocho esponjoso bañado en la mezcla perfecta de tres leches, coronado con merengue suave. Un postre que celebra la tradición con cada cucharada.",
    image: "/images/products/tres-leches.jpg",
    packagingImage: "/images/packaging/tres-leches.jpg",
    featured: false,
    ingredients: ["Leche condensada", "Leche evaporada", "Crema de leche", "Huevos", "Harina"],
    relatedProducts: ["leche-asada", "postre-de-natas", "cheesecake"],
    seo: {
      h1: "Tres Leches — Postre artesanal colombiano",
      metaTitle: "Tres Leches Artesanal | Eliana Zaia",
      metaDescription: "Tres Leches artesanal con bizcocho esponjoso y mezcla de tres leches. Postre clásico colombiano de Eliana Zaia.",
      keywords: ["tres leches", "postre tres leches colombia", "tres leches artesanal"],
      seoContent: "",
      faq: [],
    },
  },
  {
    id: "flan-de-chocolate",
    name: "Flan de Chocolate",
    weight: "90g",
    category: "premium",
    description: "Chocolate intenso en textura de flan. Para los amantes del cacao.",
    longDescription: "Nuestro Flan de Chocolate fusiona la suavidad del flan tradicional con la intensidad del cacao premium. Una experiencia de sabor que satisface hasta los paladares más exigentes. Elaborado con chocolate seleccionado y técnica artesanal.",
    image: "/images/products/flan-de-chocolate.jpg",
    packagingImage: "/images/packaging/flan-de-chocolate.jpg",
    featured: false,
    ingredients: ["Chocolate", "Leche", "Huevos", "Azúcar", "Cacao"],
    relatedProducts: ["creme-brulee", "flan-de-caramelo", "cheesecake"],
    seo: {
      h1: "Flan de Chocolate — Postre artesanal colombiano",
      metaTitle: "Flan de Chocolate Artesanal | Eliana Zaia",
      metaDescription: "Flan de Chocolate artesanal con cacao premium. Postre de Eliana Zaia disponible en las principales cadenas de Colombia.",
      keywords: ["flan de chocolate", "flan chocolate artesanal", "postre chocolate colombia"],
      seoContent: "",
      faq: [],
    },
  },
  {
    id: "mosaico",
    name: "Mosaico",
    weight: "180g",
    category: "gelatinas",
    description: "Gelatina de mosaico multicolor. Diversión y sabor en cada capa.",
    longDescription: "La Gelatina Mosaico de Eliana Zaia es una obra de arte comestible. Capas multicolores de gelatina de diferentes sabores frutales, unidas por una base cremosa. Un postre que alegra la vista y el paladar, perfecto para compartir.",
    image: "/images/products/mosaico.jpg",
    packagingImage: "/images/packaging/mosaico.jpg",
    featured: false,
    ingredients: ["Gelatina", "Leche", "Azúcar", "Saborizantes naturales", "Crema de leche"],
    relatedProducts: ["gelicloud", "gelitas", "arroz-con-leche"],
    seo: {
      h1: "Gelatina Mosaico — Postre artesanal colombiano",
      metaTitle: "Gelatina Mosaico Artesanal | Eliana Zaia",
      metaDescription: "Gelatina Mosaico multicolor artesanal con capas de sabores frutales. Postre de Eliana Zaia en supermercados de Colombia.",
      keywords: ["gelatina mosaico", "gelatina artesanal colombia", "postre gelatina"],
      seoContent: "",
      faq: [],
    },
  },
  {
    id: "arroz-con-leche",
    name: "Arroz con Leche",
    weight: "120g",
    category: "clasico",
    description: "El clásico colombiano que nunca pasa de moda. Cremoso y reconfortante.",
    longDescription: "El Arroz con Leche de Eliana Zaia es la versión definitiva de este clásico colombiano. Arroz cocido lentamente en leche fresca con canela y un toque de vainilla, logrando una cremosidad perfecta que evoca los sabores más queridos de la cocina colombiana.",
    image: "/images/products/arroz-con-leche.jpg",
    packagingImage: "/images/packaging/arroz-con-leche.jpg",
    featured: false,
    ingredients: ["Arroz", "Leche fresca", "Azúcar", "Canela", "Vainilla"],
    relatedProducts: ["leche-asada", "postre-de-natas", "tres-leches"],
    seo: {
      h1: "Arroz con Leche — Postre artesanal colombiano",
      metaTitle: "Arroz con Leche Artesanal | Eliana Zaia",
      metaDescription: "Arroz con Leche artesanal cremoso con canela y vainilla. Postre clásico colombiano de Eliana Zaia.",
      keywords: ["arroz con leche", "arroz con leche colombiano", "postre artesanal"],
      seoContent: "",
      faq: [],
    },
  },
  {
    id: "postre-de-natas",
    name: "Postre de Natas",
    weight: "120g",
    category: "clasico",
    description: "Tradición colombiana en su máxima expresión. Natas cremosas y dulces.",
    longDescription: "El Postre de Natas de Eliana Zaia honra una de las tradiciones más auténticas de la repostería colombiana. Elaborado con natas frescas cocinadas lentamente con panela y especias, es un postre que cuenta la historia de Colombia en cada bocado.",
    image: "/images/products/postre-de-natas.jpg",
    packagingImage: "/images/packaging/postre-de-natas.jpg",
    featured: false,
    ingredients: ["Natas de leche", "Panela", "Canela", "Clavos", "Azúcar"],
    relatedProducts: ["arroz-con-leche", "leche-asada", "tres-leches"],
    seo: {
      h1: "Postre de Natas — Postre artesanal colombiano",
      metaTitle: "Postre de Natas Artesanal | Eliana Zaia",
      metaDescription: "Postre de Natas artesanal con natas frescas y panela. Tradición colombiana de Eliana Zaia en las principales cadenas.",
      keywords: ["postre de natas", "postre natas colombiano", "postre tradicional colombia"],
      seoContent: "",
      faq: [],
    },
  },
  {
    id: "galletas",
    name: "Galletas",
    weight: "Variado",
    category: "snack",
    description: "Chips de chocolate y galletas rellenas. El snack perfecto para cualquier momento.",
    longDescription: "Las Galletas de Eliana Zaia combinan la calidad artesanal con la conveniencia del snack perfecto. Disponibles en versión chips de chocolate y rellenas, cada galleta es horneada con ingredientes premium para un sabor que marca la diferencia.",
    image: "/images/products/galletas.jpg",
    packagingImage: "/images/packaging/galletas.jpg",
    featured: false,
    ingredients: ["Harina de trigo", "Mantequilla", "Chips de chocolate", "Azúcar", "Huevos"],
    relatedProducts: ["gelitas", "creme-brulee", "cheesecake"],
    seo: {
      h1: "Galletas Artesanales — Snacks de Eliana Zaia",
      metaTitle: "Galletas Artesanales | Eliana Zaia",
      metaDescription: "Galletas artesanales con chips de chocolate y rellenas. Snacks premium de Eliana Zaia en supermercados de Colombia.",
      keywords: ["galletas artesanales", "galletas chocolate colombia", "snack artesanal"],
      seoContent: "",
      faq: [],
    },
  },
  {
    id: "gelicloud",
    name: "GeliCloud",
    weight: "180g",
    category: "gelatinas",
    description: "Gelatina mosaico con textura de nube. Suave, cremosa y colorida.",
    longDescription: "GeliCloud es la innovación de Eliana Zaia en el mundo de las gelatinas. Una textura única que combina la firmeza de la gelatina con la suavidad de una nube, en una presentación mosaico que deleita la vista. Un postre que los niños y adultos aman por igual.",
    image: "/images/products/gelicloud.jpg",
    packagingImage: "/images/packaging/gelicloud.jpg",
    featured: false,
    ingredients: ["Gelatina", "Crema de leche", "Azúcar", "Saborizantes naturales"],
    relatedProducts: ["mosaico", "gelitas", "arroz-con-leche"],
    seo: {
      h1: "GeliCloud — Gelatina mosaico artesanal",
      metaTitle: "GeliCloud Gelatina Mosaico | Eliana Zaia",
      metaDescription: "GeliCloud, gelatina mosaico con textura de nube. Postre artesanal innovador de Eliana Zaia en supermercados de Colombia.",
      keywords: ["gelatina mosaico", "gelicloud", "gelatina artesanal colombia"],
      seoContent: "",
      faq: [],
    },
  },
  {
    id: "gelitas",
    name: "Gelitas",
    weight: "150g",
    category: "gelatinas",
    description: "Gelatinas individuales en porciones perfectas. Prácticas y deliciosas.",
    longDescription: "Las Gelitas de Eliana Zaia son porciones individuales de gelatina artesanal, perfectas para loncheras, snacks o postres rápidos. Sabores frutales naturales en una presentación práctica que mantiene toda la calidad artesanal de nuestra marca.",
    image: "/images/products/gelitas.jpg",
    packagingImage: "/images/packaging/gelitas.jpg",
    featured: false,
    ingredients: ["Gelatina", "Azúcar", "Saborizantes naturales", "Ácido cítrico"],
    relatedProducts: ["mosaico", "gelicloud", "galletas"],
    seo: {
      h1: "Gelitas — Gelatinas individuales artesanales",
      metaTitle: "Gelitas Gelatinas Individuales | Eliana Zaia",
      metaDescription: "Gelitas, gelatinas individuales artesanales en porciones perfectas. Snack saludable de Eliana Zaia en supermercados de Colombia.",
      keywords: ["gelitas", "gelatina individual", "gelatina artesanal porcion"],
      seoContent: "",
      faq: [],
    },
  },
  {
    id: "flan-de-caramelo",
    name: "Flan de Caramelo",
    weight: "120g",
    category: "clasico",
    description: "El flan de toda la vida, con caramelo dorado y textura perfecta.",
    longDescription: "El Flan de Caramelo de Eliana Zaia es la interpretación definitiva del postre más querido de Latinoamérica. Textura sedosa, caramelo dorado y un sabor que transporta. Elaborado con la receta que ha conquistado las mesas colombianas por más de 15 años.",
    image: "/images/products/flan-de-caramelo.jpg",
    packagingImage: "/images/packaging/flan-de-caramelo.jpg",
    featured: false,
    ingredients: ["Leche", "Huevos", "Azúcar", "Vainilla", "Caramelo"],
    relatedProducts: ["flan-de-chocolate", "creme-brulee", "leche-asada"],
    seo: {
      h1: "Flan de Caramelo — Postre artesanal colombiano",
      metaTitle: "Flan de Caramelo Artesanal | Eliana Zaia",
      metaDescription: "Flan de Caramelo artesanal con caramelo dorado y textura sedosa. Postre clásico de Eliana Zaia en las principales cadenas de Colombia.",
      keywords: ["flan de caramelo", "flan artesanal", "flan caramelo colombia"],
      seoContent: "",
      faq: [],
    },
  },
];

export const ALLIES: Ally[] = [
  { name: "PriceSmart", logo: "/images/allies/pricesmart.svg" },
  { name: "Grupo Exito", logo: "/images/allies/exito.svg" },
  { name: "Mercaldas", logo: "/images/allies/mercaldas.svg" },
  { name: "Isimo Mercado", logo: "/images/allies/isimo.svg" },
  { name: "Kokoriko", logo: "/images/allies/kokoriko.svg" },
  { name: "Cencosud", logo: "/images/allies/cencosud.svg" },
  { name: "Tiendas D1", logo: "/images/allies/d1.svg" },
  { name: "Tiendas Ara", logo: "/images/allies/ara.svg" },
];

export const GRUPO_RADICI: GrupoEmpresa[] = [
  { name: "Eliana Zaia", description: "Reposteria EZ — Colombia", logo: "/images/grupo/eliana-zaia.svg" },
  { name: "El Tinto", description: "", logo: "/images/grupo/el-tinto.svg" },
  { name: "EZ Treats", description: "Fabrica de Postres — Lima, Peru", logo: "/images/grupo/ez-treats.svg" },
  { name: "Moldeza", description: "", logo: "/images/grupo/moldeza.svg" },
  { name: "Radici Wealth Management", description: "", logo: "/images/grupo/radici-wm.svg" },
];

export const PRODUCT_CATEGORIES = [
  { id: "all", label: "Todos" },
  { id: "premium", label: "Premium" },
  { id: "clasico", label: "Clasicos" },
  { id: "gelatinas", label: "Gelatinas" },
  { id: "snack", label: "Snacks" },
] as const;

export const NAV_LINKS = [
  { href: "/productos", label: "Productos" },
  { href: "/para-empresas", label: "Para Empresas" },
  { href: "/nosotros", label: "Nosotros" },
  { href: "/grupo-radici", label: "Grupo Radici" },
  { href: "/blog", label: "Blog" },
  { href: "/contacto", label: "Contacto" },
] as const;

export const FOOTER_LINKS = {
  productos: [
    { href: "/productos", label: "Catalogo" },
    { href: "/donde-comprar", label: "Donde Comprar" },
  ],
  empresa: [
    { href: "/para-empresas", label: "Para Empresas" },
    { href: "/para-empresas/maquila", label: "Maquila" },
    { href: "/para-empresas/distribucion", label: "Distribucion" },
  ],
  nosotros: [
    { href: "/nosotros", label: "Nuestra Historia" },
    { href: "/grupo-radici", label: "Grupo Radici" },
    { href: "/blog", label: "Blog" },
  ],
  contacto: [
    { href: "/contacto", label: "Contacto" },
    { href: "/quiero-ser-proveedor", label: "Ser Proveedor" },
    { href: "/trabaja-con-nosotros", label: "Trabaja con Nosotros" },
  ],
} as const;
